# Generated by Django 4.0.3 on 2022-04-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('players', models.TextField()),
                ('players_count', models.IntegerField()),
                ('board', models.TextField()),
                ('playing_player', models.TextField()),
            ],
        ),
    ]
